baseURL = "https://aditya3w3733.in"
languageCode = "en-us"
title = "Aditya3w3733's Blog"
theme = "congo"

# Outputs
[outputs]
home = ["HTML", "RSS", "JSON"]

# Pagination
paginate = 10

# Permalinks
[permalinks]
posts = "/blog/:year/:title/"

# Module imports
[module]
[[module.imports]]
path = "congo"

# Site parameters
[params]
description = "Welcome to Aditya's blog"
authorname = "S Aditya"
defaultTheme = "dark"
enableSearch = true
navbarTitle = "Aditya3w3733's Blog"

[params.homepage]
layout = "profile"
showRecent = true

[params.footer]
showCopyright = false
showThemeAttribution = false
showAppearanceSwitcher = false

[params.author]
name = "S Aditya"
image = "img/author.jpg"
headline = "DevOps Intern & Tech Enthusiast"
bio = "Hello! I'm Aditya, a passionate devops intern with interests in cloud computing, AI, and open-source technologies. I love exploring new tech stacks and sharing my learnings through this blog. When I'm not coding, you can find me playing chess or reading sci-fi novels."

[params.author.social]
github = "https://github.com/aditya3w3733"
linkedin = "https://www.linkedin.com/in/saditya3733"
mastodon = "https://mastodon.social/@aditya3w3733"

# Main menu
[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10

[[menu.main]]
name = "Posts"
pageRef = "posts"
weight = 20
