baseURL = "https://aditya3w3733.in"
languageCode = "en-us"
title = "Aditya3w3733's Blog"
theme = "congo"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
description = "Welcome to Aditya's blog"

authorname = " S Aditya"

# Set default theme color (can be overridden by user)
defaultTheme = "dark"

# Enable search
enableSearch = true

# Navbar title
navbarTitle = "Aditya3w3733's Blog"

# Footer configuration
[params.footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true

# Enable comments via Disqus
disqusShortname = ""

# Homepage configuration
[params.homepage]
layout = "profile" # Use profile layout
showRecent = true

# Author configuration (for profile page)
[params.author]
name = "Aditya"
image = "img/author.jpg"                                                                                                                                                                                                                                                          # Place your photo in the static/img directory
headline = "DevOps Intern & Tech Enthusiast"
bio = "Hello! I'm Aditya, a passionate software developer with interests in cloud computing, AI, and open-source technologies. I love exploring new tech stacks and sharing my learnings through this blog. When I'm not coding, you can playing chess or reading sci-fi novels."

[params.author.social]
github = "https://github.com/aditya3w3733"
linkedin = "https://www.linkedin.com/in/saditya3733"
mastodon = "https://mastodon.social/@aditya3w3733"

# Main menu items
[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10

[[menu.main]]
name = "Posts"
pageRef = "posts"
weight = 20

[[menu.main]]
name = "Tags"
pageRef = "tags"
weight = 30

# Pagination
paginate = 10


[module]
[[module.imports]]
path = "congo"
