baseURL = "https://aditya3w3733.in"
languageCode = "en-us"
title = "Aditya3w3733's Blog"
theme = "congo"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
description = "Exploring DevOps, Cloud, and Beyond"
authorname = "S Aditya"
defaultTheme = "dark"
enableSearch = true
navbarTitle = "Aditya3w3733"

[params.footer]
showCopyright = false
showThemeAttribution = false
showAppearanceSwitcher = false

[params.homepage]
layout = "custom"
showRecent = true

[params.author]
name = "S Aditya"
image = "img/author.jpg"
headline = "DevOps Engineer & Tech Explorer"
bio = "Hello! I'm Aditya, a DevOps engineer passionate about cloud computing, AI, and open-source technologies. Join me as I share insights and experiences from my tech journey."

[params.author.social]
github = "https://github.com/aditya3w3733"
linkedin = "https://www.linkedin.com/in/saditya3733"
mastodon = "https://mastodon.social/@aditya3w3733"

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10

[[menu.main]]
name = "Blog"
pageRef = "posts"
weight = 20

[permalinks]
posts = "/blog/:year/:title/"

[taxonomies]
tag = "tags"

[module]
[[module.imports]]
path = "github.com/jpanther/congo/v2"
